### ISSUE TITLE
Pressing Enter should create a tag directly from the entry field

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Flashcards#6]
### Describe the bug

Pressing the Enter key should create a Tag directly from the input field filled in by the user, without having to search for another interface button to save it.

### To Reproduce

Currently you have to tap the + button once, then type and press the + button again, which is not very intuitive (and creates another tag)…

### Expected behavior

When creating a Tag, you should only have to tap the + button once, then type and press Enter

### Additional context

![Capture d’écran du 2024-02-25 14-21-19](https://github.com/david-swift/Flashcards/assets/95506494/965396bc-b425-4b28-a18f-42d16f3f3655)

**Comment by david-swift** [comment]
Thanks so much for opening this issue, @rene-coty! I've fixed it in the commit 4d8247b. The newly added tag (or keyword, both views are built on the same code) now additionally also gets the focus. A tag/keyword can be added by pressing enter inside of a tag/keyword entry.

[Screencast from 2024-02-25 14-49-43.webm](https://github.com/david-swift/Flashcards/assets/106754840/a6962270-3702-419c-84a2-02295eeca02d)

**Comment by david-swift** [comment]
@rene-coty, thanks again so much for your suggestion! I applied the same principle to the navigation in the edit view (and creating new flashcards), and it feels so natural!

[Screencast from 2024-02-25 15-50-43.webm](https://github.com/david-swift/Flashcards/assets/106754840/2651c540-f661-431a-8c32-6bb7c3f910dd)

**Comment by david-swift** [comment]
Ah sorry, I think I misunderstood this issue (I think the unrelated changes improve the UX as well). Currently, there's no requirement to press enter after having typed a tag's name, the tags view gets updated automatically. Since this does not seem to be intuitive, do you think a UI more similar to the one seen in Errands would be a better approach?

[Screencast from 2024-02-25 21-27-38.webm](https://github.com/david-swift/Flashcards/assets/106754840/2f2aad97-449d-419a-a72b-ca708d6dc9c8)

**Comment by rene-coty** [comment]
Maybe I wasn't very clear since I'm not a native English speaker, but I think you did answer my issue though :) it's more easy now to browse the UI fluently with a keyboard

**Comment by david-swift** [comment]
Oh :see_no_evil: :rofl: - I'll close the issue again then.
