### ISSUE TITLE
Add tooltips to the UI

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Flashcards#7]
Most of the buttons lack 'tooltips' to indicate what they trigger, which makes understanding the app's features (sometimes) not evident…
E.g. I was confused by the button that allows importing from Quizlet/Anki, thinking it created a backup of my Flashcards set; same for the 'export' button next to the 'delete' one 😅

**Comment by david-swift** [comment]
Thanks for reporting that, I'll add a tooltip to every icon-only button. What icons do you think would communicate the import/export features better?

For importing, I found the following two icons that could be more suitable:
![Screenshot from 2024-02-25 21-07-54](https://github.com/david-swift/Flashcards/assets/106754840/01766ddd-85ee-4667-97c6-98c95b773b9e)
![Screenshot from 2024-02-25 21-12-08](https://github.com/david-swift/Flashcards/assets/106754840/553cb4c1-f558-40e4-8bd8-f22619cece4e)

This one feels less suitable, but it may be an option as well:
![Screenshot from 2024-02-25 21-12-24](https://github.com/david-swift/Flashcards/assets/106754840/44d4b9e8-a2c7-4622-865d-69a59467b2d7)

In Errands, the following icon is used for exporting:
![Screenshot from 2024-02-25 21-11-56](https://github.com/david-swift/Flashcards/assets/106754840/672865cc-fb06-4d3e-8b44-61b636840227)

Maybe, the "copy" icon works as well since exporting is about copying a set's content:
![Screenshot from 2024-02-25 21-14-19](https://github.com/david-swift/Flashcards/assets/106754840/b988db19-c5ab-4571-880f-4dd21f4acfdc)

What do you think about those icons? Which one do you prefer, or do you think there's another one I should consider?

**Comment by rene-coty** [comment]
Thanks for your reply! The export icon in itself seems pretty good to me, I was especially confused by the import icon. Your first proposition (the arrow-into-box symbolic) looks very adequate though.

**Comment by david-swift** [comment]
I fixed this in the commit 72fae89. Thanks again for opening the issue!
